# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: backend.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rbackend.proto\"?\n\x04Post\x12\x17\n\x06status\x18\x01 \x01(\x0e\x32\x07.Status\x12\x0e\n\x06user_1\x18\x02 \x01(\x05\x12\x0e\n\x06user_2\x18\x03 \x01(\x05\"y\n\nUpdatePost\x12\x13\n\x04post\x18\x01 \x01(\x0b\x32\x05.Post\x12\x15\n\ruser_1_points\x18\x02 \x01(\x05\x12\x17\n\x06status\x18\x03 \x01(\x0e\x32\x07.Status\x12\x11\n\tfinish_at\x18\x04 \x01(\t\x12\x13\n\x0buser_1_turn\x18\x05 \x01(\x08\"t\n\x08MovePost\x12\x0c\n\x04game\x18\x01 \x01(\x05\x12\x0c\n\x04user\x18\x02 \x01(\x05\x12\x12\n\nchecker_id\x18\x03 \x01(\x05\x12\x15\n\rnew_positions\x18\x04 \x03(\t\x12\x0f\n\x07is_king\x18\x05 \x01(\x08\x12\x10\n\x08is_white\x18\x06 \x01(\x08\"\x1f\n\x0cGameResponce\x12\x0f\n\x07message\x18\x01 \x01(\t\"&\n\x13\x43heckerMoveResponce\x12\x0f\n\x07message\x18\x01 \x01(\t*3\n\x06Status\x12\x0b\n\x07\x43REATED\x10\x00\x12\x0e\n\nIN_PROCESS\x10\x01\x12\x0c\n\x08\x46INISHED\x10\x03\x32\x93\x01\n\x07WsProto\x12\'\n\x0f\x63reateGameEvent\x12\x05.Post\x1a\r.GameResponce\x12+\n\reditGameEvent\x12\x0b.UpdatePost\x1a\r.GameResponce\x12\x32\n\x0f\x63reateMoveEvent\x12\t.MovePost\x1a\x14.CheckerMoveResponceb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'backend_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _STATUS._serialized_start=396
  _STATUS._serialized_end=447
  _POST._serialized_start=17
  _POST._serialized_end=80
  _UPDATEPOST._serialized_start=82
  _UPDATEPOST._serialized_end=203
  _MOVEPOST._serialized_start=205
  _MOVEPOST._serialized_end=321
  _GAMERESPONCE._serialized_start=323
  _GAMERESPONCE._serialized_end=354
  _CHECKERMOVERESPONCE._serialized_start=356
  _CHECKERMOVERESPONCE._serialized_end=394
  _WSPROTO._serialized_start=450
  _WSPROTO._serialized_end=597
# @@protoc_insertion_point(module_scope)
